# https://github.com/habx/devops-repo-shared-configs/blob/dev/github-settings/ts-lib-client-public.yml
# last_update: 2022-08-27
_extends: devops-repo-shared-configs:github-settings/ts-lib-client-public.yml
